import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";

/**
 * Dynamic robots.txt generated by Next.js at build time.
 *
 * Always uses the real production URL — no more localhost leaking
 * into the crawl directives.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
