#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# Find available ports for all project services to avoid collisions.
# Skips ports already held by this project's own Docker containers
# so re-running the script is idempotent.
#
#   source scripts/ports.sh          # export into current shell
#   source scripts/ports.sh --print  # also print the chosen ports
#   source scripts/ports.sh --env    # also write .env.local for host tools
# ──────────────────────────────────────────────────────────────
set -euo pipefail

PROJECT_CONTAINERS=(
  personal-site-app
  personal-site-dev
  personal-site-mailpit
  personal-site-odoo
  personal-site-odoo-db
)

# ── helpers ───────────────────────────────────────────────────

# Collect ports held by this project's own Docker containers so
# we can ignore them when checking for conflicts.
_own_ports=""
_collect_own_ports() {
  if command -v docker &>/dev/null; then
    for cname in "${PROJECT_CONTAINERS[@]}"; do
      local mapping
      mapping=$(docker port "$cname" 2>/dev/null || true)
      if [ -n "$mapping" ]; then
        # docker port output: "3000/tcp -> 0.0.0.0:3000"
        while IFS= read -r line; do
          local p
          p=$(echo "$line" | grep -oP '(?<=:)\d+$' || true)
          [ -n "$p" ] && _own_ports="${_own_ports} ${p} "
        done <<< "$mapping"
      fi
    done
  fi
}

_is_own_port() {
  [[ "$_own_ports" == *" $1 "* ]]
}

# Check if a port is in use (by something other than our own containers).
_port_busy() {
  local port=$1

  # If it's our own container, it's not "busy"
  if _is_own_port "$port"; then
    return 1
  fi

  # Try ss first (Linux), fall back to lsof (macOS/BSD)
  if command -v ss &>/dev/null; then
    ss -tln 2>/dev/null | grep -qE "(:${port})\b" && return 0
  elif command -v lsof &>/dev/null; then
    lsof -iTCP:"$port" -sTCP:LISTEN -P -n &>/dev/null && return 0
  elif command -v netstat &>/dev/null; then
    netstat -tln 2>/dev/null | grep -qE ":${port}\s" && return 0
  fi

  return 1
}

# Walk from $1 up to $1+50 looking for a free port.
_find_port() {
  local port=$1
  local max=$((port + 50))
  while [ "$port" -lt "$max" ]; do
    if ! _port_busy "$port"; then
      echo "$port"
      return 0
    fi
    port=$((port + 1))
  done
  # Exhausted range — return the default and let Docker fail loudly
  echo "$1"
  return 1
}

# ── collect our own container ports ───────────────────────────
_collect_own_ports

# ── resolve each service port (allow manual override) ─────────
export APP_PORT="${APP_PORT:-$(_find_port 3000)}"
export MAILPIT_UI_PORT="${MAILPIT_UI_PORT:-$(_find_port 8025)}"
export MAILPIT_SMTP_PORT="${MAILPIT_SMTP_PORT:-$(_find_port 1025)}"
export ODOO_PORT="${ODOO_PORT:-$(_find_port 8069)}"
export ODOO_DB_PORT="${ODOO_DB_PORT:-$(_find_port 5434)}"

# ── derived URLs used by Playwright / e2e / host-side tools ───
export BASE_URL="http://localhost:${APP_PORT}"
export MAILPIT_API="http://localhost:${MAILPIT_UI_PORT}/api/v1"
export ODOO_URL="http://localhost:${ODOO_PORT}"
export NEXT_PUBLIC_SITE_URL="http://localhost:${APP_PORT}"

# ── optional: write .env.local so host-side tools get the ports ─
_write_env_local() {
  local f
  f="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.local"
  cat > "$f" <<ENVEOF
# Auto-generated by scripts/ports.sh — DO NOT EDIT
# These point to Docker-mapped ports on the host for local tooling
NEXT_PUBLIC_SITE_URL=http://localhost:${APP_PORT}
ENVEOF
}

# ── output ────────────────────────────────────────────────────
if [[ "${1:-}" == "--print" || "${1:-}" == "--env" ]]; then
  cat <<EOF

  personal-dev-page ports
  ───────────────────────────
  App (Next.js)  : ${APP_PORT}   → http://localhost:${APP_PORT}
  Mailpit UI     : ${MAILPIT_UI_PORT}   → http://localhost:${MAILPIT_UI_PORT}
  Mailpit SMTP   : ${MAILPIT_SMTP_PORT}
  Odoo CRM       : ${ODOO_PORT}   → http://localhost:${ODOO_PORT}
  Odoo PostgreSQL: ${ODOO_DB_PORT}
  ───────────────────────────

EOF
fi

if [[ "${1:-}" == "--env" ]]; then
  _write_env_local
  echo "  Wrote .env.local with host-side connection strings."
  echo ""
fi
